// <auto-generated />
using System;
using DatabaseComparison.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseComparison.Data.Migrations.MySql
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20221114193037_MySql")]
    partial class MySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseComparison.Data.Entities.HeartRateMonitor<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Average")
                        .HasColumnType("int")
                        .HasColumnName("average");

                    b.Property<int>("Max")
                        .HasColumnType("int")
                        .HasColumnName("max");

                    b.Property<int>("Min")
                        .HasColumnType("int")
                        .HasColumnName("min");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registered_at");

                    b.Property<string>("SmartWatchId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("smart_watch_id");

                    b.HasKey("Id")
                        .HasName("pk_heart_rate_monitors");

                    b.HasIndex("RegisteredAt")
                        .HasDatabaseName("ix_heart_rate_monitors_registered_at");

                    b.HasIndex("SmartWatchId")
                        .HasDatabaseName("ix_heart_rate_monitors_smart_watch_id");

                    b.ToTable("heart_rate_monitors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
