// <auto-generated />
using System;
using DatabaseComparison.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseComparison.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseComparison.Data.Entities.HeartRateMonitor<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Average")
                        .HasColumnType("integer")
                        .HasColumnName("average");

                    b.Property<int>("Max")
                        .HasColumnType("integer")
                        .HasColumnName("max");

                    b.Property<int>("Min")
                        .HasColumnType("integer")
                        .HasColumnName("min");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SmartWatchId")
                        .HasColumnType("text")
                        .HasColumnName("smart_watch_id");

                    b.HasKey("Id")
                        .HasName("pk_heart_rate_monitors");

                    b.HasIndex("RegisteredAt")
                        .HasDatabaseName("ix_heart_rate_monitors_registered_at");

                    b.HasIndex("SmartWatchId")
                        .HasDatabaseName("ix_heart_rate_monitors_smart_watch_id");

                    b.ToTable("heart_rate_monitors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
